// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 12 Dec 2023 23:18:54 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "../ugui/ugui.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// UG_OBJECT_UPDATE_4efebda8 is a proxy for callback UG_OBJECT_UPDATE.
void UG_OBJECT_UPDATE_4efebda8(UG_WINDOW* arg0, UG_OBJECT* arg1);

// UG_Message_Callback_1fd3c4e6 is a proxy for callback UG_Message_Callback.
void UG_Message_Callback_1fd3c4e6(UG_MESSAGE* arg0);

// UG_GUI_PSET_37bded48 is a proxy for callback UG_GUI_PSET.
void UG_GUI_PSET_37bded48(short int arg0, short int arg1, unsigned int arg2);

// UG_Init_Callback_19d8bb9f is a proxy for callback UG_Init_Callback.
void UG_Init_Callback_19d8bb9f(short int arg0, short int arg1, unsigned int arg2);

