// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 12 Dec 2023 23:18:54 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void UG_OBJECT_UPDATE_4efebda8(UG_WINDOW* arg0, UG_OBJECT* arg1) {
	uG_OBJECT_UPDATE4EFEBDA8(arg0, arg1);
}

void UG_Message_Callback_1fd3c4e6(UG_MESSAGE* arg0) {
	uG_Message_Callback1FD3C4E6(arg0);
}

void UG_GUI_PSET_37bded48(short int arg0, short int arg1, unsigned int arg2) {
	uG_GUI_PSET37BDED48(arg0, arg1, arg2);
}

void UG_Init_Callback_19d8bb9f(short int arg0, short int arg1, unsigned int arg2) {
	uG_Init_Callback19D8BB9F(arg0, arg1, arg2);
}

