// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 12 Dec 2023 23:18:54 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package ug

/*
#cgo LDFLAGS: -L../ugui/build -lugui
#include "../ugui/ugui.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// ALIGN_H_LEFT as defined in ugui/ugui.h:138
	ALIGN_H_LEFT = (1 << 0)
	// ALIGN_H_CENTER as defined in ugui/ugui.h:139
	ALIGN_H_CENTER = (1 << 1)
	// ALIGN_H_RIGHT as defined in ugui/ugui.h:140
	ALIGN_H_RIGHT = (1 << 2)
	// ALIGN_V_TOP as defined in ugui/ugui.h:141
	ALIGN_V_TOP = (1 << 3)
	// ALIGN_V_CENTER as defined in ugui/ugui.h:142
	ALIGN_V_CENTER = (1 << 4)
	// ALIGN_V_BOTTOM as defined in ugui/ugui.h:143
	ALIGN_V_BOTTOM = (1 << 5)
	// ALIGN_BOTTOM_RIGHT as defined in ugui/ugui.h:144
	ALIGN_BOTTOM_RIGHT = (ALIGN_V_BOTTOM | ALIGN_H_RIGHT)
	// ALIGN_BOTTOM_CENTER as defined in ugui/ugui.h:145
	ALIGN_BOTTOM_CENTER = (ALIGN_V_BOTTOM | ALIGN_H_CENTER)
	// ALIGN_BOTTOM_LEFT as defined in ugui/ugui.h:146
	ALIGN_BOTTOM_LEFT = (ALIGN_V_BOTTOM | ALIGN_H_LEFT)
	// ALIGN_CENTER_RIGHT as defined in ugui/ugui.h:147
	ALIGN_CENTER_RIGHT = (ALIGN_V_CENTER | ALIGN_H_RIGHT)
	// ALIGN_CENTER as defined in ugui/ugui.h:148
	ALIGN_CENTER = (ALIGN_V_CENTER | ALIGN_H_CENTER)
	// ALIGN_CENTER_LEFT as defined in ugui/ugui.h:149
	ALIGN_CENTER_LEFT = (ALIGN_V_CENTER | ALIGN_H_LEFT)
	// ALIGN_TOP_RIGHT as defined in ugui/ugui.h:150
	ALIGN_TOP_RIGHT = (ALIGN_V_TOP | ALIGN_H_RIGHT)
	// ALIGN_TOP_CENTER as defined in ugui/ugui.h:151
	ALIGN_TOP_CENTER = (ALIGN_V_TOP | ALIGN_H_CENTER)
	// ALIGN_TOP_LEFT as defined in ugui/ugui.h:152
	ALIGN_TOP_LEFT = (ALIGN_V_TOP | ALIGN_H_LEFT)
	// OBJ_ID_0 as defined in ugui/ugui.h:155
	OBJ_ID_0 = 0
	// OBJ_ID_1 as defined in ugui/ugui.h:156
	OBJ_ID_1 = 1
	// OBJ_ID_2 as defined in ugui/ugui.h:157
	OBJ_ID_2 = 2
	// OBJ_ID_3 as defined in ugui/ugui.h:158
	OBJ_ID_3 = 3
	// OBJ_ID_4 as defined in ugui/ugui.h:159
	OBJ_ID_4 = 4
	// OBJ_ID_5 as defined in ugui/ugui.h:160
	OBJ_ID_5 = 5
	// OBJ_ID_6 as defined in ugui/ugui.h:161
	OBJ_ID_6 = 6
	// OBJ_ID_7 as defined in ugui/ugui.h:162
	OBJ_ID_7 = 7
	// OBJ_ID_8 as defined in ugui/ugui.h:163
	OBJ_ID_8 = 8
	// OBJ_ID_9 as defined in ugui/ugui.h:164
	OBJ_ID_9 = 9
	// OBJ_ID_10 as defined in ugui/ugui.h:165
	OBJ_ID_10 = 10
	// OBJ_ID_11 as defined in ugui/ugui.h:166
	OBJ_ID_11 = 11
	// OBJ_ID_12 as defined in ugui/ugui.h:167
	OBJ_ID_12 = 12
	// OBJ_ID_13 as defined in ugui/ugui.h:168
	OBJ_ID_13 = 13
	// OBJ_ID_14 as defined in ugui/ugui.h:169
	OBJ_ID_14 = 14
	// OBJ_ID_15 as defined in ugui/ugui.h:170
	OBJ_ID_15 = 15
	// OBJ_ID_16 as defined in ugui/ugui.h:171
	OBJ_ID_16 = 16
	// OBJ_ID_17 as defined in ugui/ugui.h:172
	OBJ_ID_17 = 17
	// OBJ_ID_18 as defined in ugui/ugui.h:173
	OBJ_ID_18 = 18
	// OBJ_ID_19 as defined in ugui/ugui.h:174
	OBJ_ID_19 = 19
	// UG_RESULT_FAIL as defined in ugui/ugui.h:179
	UG_RESULT_FAIL = -1
	// UG_RESULT_OK as defined in ugui/ugui.h:180
	UG_RESULT_OK = 0
	// BMP_BPP_1 as defined in ugui/ugui.h:219
	BMP_BPP_1 = (1 << 0)
	// BMP_BPP_2 as defined in ugui/ugui.h:220
	BMP_BPP_2 = (1 << 1)
	// BMP_BPP_4 as defined in ugui/ugui.h:221
	BMP_BPP_4 = (1 << 2)
	// BMP_BPP_8 as defined in ugui/ugui.h:222
	BMP_BPP_8 = (1 << 3)
	// BMP_BPP_16 as defined in ugui/ugui.h:223
	BMP_BPP_16 = (1 << 4)
	// BMP_BPP_32 as defined in ugui/ugui.h:224
	BMP_BPP_32 = (1 << 5)
	// BMP_RGB888 as defined in ugui/ugui.h:225
	BMP_RGB888 = (1 << 0)
	// BMP_RGB565 as defined in ugui/ugui.h:226
	BMP_RGB565 = (1 << 1)
	// BMP_RGB555 as defined in ugui/ugui.h:227
	BMP_RGB555 = (1 << 2)
	// OBJ_TYPE_NONE as defined in ugui/ugui.h:284
	OBJ_TYPE_NONE = 0
	// OBJ_TYPE_BUTTON as defined in ugui/ugui.h:285
	OBJ_TYPE_BUTTON = 1
	// OBJ_TYPE_TEXTBOX as defined in ugui/ugui.h:286
	OBJ_TYPE_TEXTBOX = 2
	// OBJ_TYPE_IMAGE as defined in ugui/ugui.h:287
	OBJ_TYPE_IMAGE = 3
	// OBJ_TYPE_CHECKBOX as defined in ugui/ugui.h:288
	OBJ_TYPE_CHECKBOX = 4
	// OBJ_TYPE_TITLE as defined in ugui/ugui.h:289
	OBJ_TYPE_TITLE = 5
	// OBJ_EVENT_NONE as defined in ugui/ugui.h:292
	OBJ_EVENT_NONE = 0
	// OBJ_EVENT_CLICKED as defined in ugui/ugui.h:293
	OBJ_EVENT_CLICKED = 1
	// OBJ_EVENT_PRESSED as defined in ugui/ugui.h:300
	OBJ_EVENT_PRESSED = 4
	// OBJ_EVENT_RELEASED as defined in ugui/ugui.h:301
	OBJ_EVENT_RELEASED = 5
	// OBJ_EVENT_DRAG as defined in ugui/ugui.h:302
	OBJ_EVENT_DRAG = 6
	// OBJ_EVENT_FOCUS_ENTER as defined in ugui/ugui.h:303
	OBJ_EVENT_FOCUS_ENTER = 7
	// OBJ_EVENT_FOCUS_LEAVE as defined in ugui/ugui.h:304
	OBJ_EVENT_FOCUS_LEAVE = 8
	// OBJ_STATE_FREE as defined in ugui/ugui.h:307
	OBJ_STATE_FREE = (1 << 0)
	// OBJ_STATE_VALID as defined in ugui/ugui.h:308
	OBJ_STATE_VALID = (1 << 1)
	// OBJ_STATE_BUSY as defined in ugui/ugui.h:309
	OBJ_STATE_BUSY = (1 << 2)
	// OBJ_STATE_VISIBLE as defined in ugui/ugui.h:310
	OBJ_STATE_VISIBLE = (1 << 3)
	// OBJ_STATE_ENABLE as defined in ugui/ugui.h:311
	OBJ_STATE_ENABLE = (1 << 4)
	// OBJ_STATE_UPDATE as defined in ugui/ugui.h:312
	OBJ_STATE_UPDATE = (1 << 5)
	// OBJ_STATE_REDRAW as defined in ugui/ugui.h:313
	OBJ_STATE_REDRAW = (1 << 6)
	// OBJ_STATE_TOUCH_ENABLE as defined in ugui/ugui.h:314
	OBJ_STATE_TOUCH_ENABLE = (1 << 7)
	// OBJ_STATE_INIT as defined in ugui/ugui.h:315
	OBJ_STATE_INIT = (OBJ_STATE_FREE | OBJ_STATE_VALID)
	// OBJ_STATE_FOCUSED as defined in ugui/ugui.h:316
	OBJ_STATE_FOCUSED = (1 << 8)
	// OBJ_FOCUS_STATE_CHANGED as defined in ugui/ugui.h:319
	OBJ_FOCUS_STATE_CHANGED = (1 << 0)
	// OBJ_FOCUS_STATE_ENTER as defined in ugui/ugui.h:320
	OBJ_FOCUS_STATE_ENTER = (1 << 1)
	// OBJ_FOCUS_STATE_LEAVE as defined in ugui/ugui.h:321
	OBJ_FOCUS_STATE_LEAVE = (1 << 2)
	// OBJ_TOUCH_STATE_CHANGED as defined in ugui/ugui.h:324
	OBJ_TOUCH_STATE_CHANGED = (1 << 0)
	// OBJ_TOUCH_STATE_PRESSED_ON_OBJECT as defined in ugui/ugui.h:325
	OBJ_TOUCH_STATE_PRESSED_ON_OBJECT = (1 << 1)
	// OBJ_TOUCH_STATE_PRESSED_OUTSIDE_OBJECT as defined in ugui/ugui.h:326
	OBJ_TOUCH_STATE_PRESSED_OUTSIDE_OBJECT = (1 << 2)
	// OBJ_TOUCH_STATE_RELEASED_ON_OBJECT as defined in ugui/ugui.h:327
	OBJ_TOUCH_STATE_RELEASED_ON_OBJECT = (1 << 3)
	// OBJ_TOUCH_STATE_RELEASED_OUTSIDE_OBJECT as defined in ugui/ugui.h:328
	OBJ_TOUCH_STATE_RELEASED_OUTSIDE_OBJECT = (1 << 4)
	// OBJ_TOUCH_STATE_IS_PRESSED_ON_OBJECT as defined in ugui/ugui.h:329
	OBJ_TOUCH_STATE_IS_PRESSED_ON_OBJECT = (1 << 5)
	// OBJ_TOUCH_STATE_IS_PRESSED as defined in ugui/ugui.h:330
	OBJ_TOUCH_STATE_IS_PRESSED = (1 << 6)
	// OBJ_TOUCH_STATE_CLICK_ON_OBJECT as defined in ugui/ugui.h:331
	OBJ_TOUCH_STATE_CLICK_ON_OBJECT = (1 << 7)
	// OBJ_TOUCH_STATE_DRAG_OBJECT as defined in ugui/ugui.h:332
	OBJ_TOUCH_STATE_DRAG_OBJECT = (1 << 8)
	// OBJ_TOUCH_STATE_INIT as defined in ugui/ugui.h:333
	OBJ_TOUCH_STATE_INIT = 0
	// UG_MOVE_FOCUS_NONE as defined in ugui/ugui.h:335
	UG_MOVE_FOCUS_NONE = 0
	// UG_MOVE_FOCUS_UP as defined in ugui/ugui.h:336
	UG_MOVE_FOCUS_UP = 1
	// UG_MOVE_FOCUS_DOWN as defined in ugui/ugui.h:337
	UG_MOVE_FOCUS_DOWN = 2
	// UG_MOVE_FOCUS_LEFT as defined in ugui/ugui.h:338
	UG_MOVE_FOCUS_LEFT = 3
	// UG_MOVE_FOCUS_RIGHT as defined in ugui/ugui.h:339
	UG_MOVE_FOCUS_RIGHT = 4
	// BTN_ID_0 as defined in ugui/ugui.h:419
	BTN_ID_0 = OBJ_ID_0
	// BTN_ID_1 as defined in ugui/ugui.h:420
	BTN_ID_1 = OBJ_ID_1
	// BTN_ID_2 as defined in ugui/ugui.h:421
	BTN_ID_2 = OBJ_ID_2
	// BTN_ID_3 as defined in ugui/ugui.h:422
	BTN_ID_3 = OBJ_ID_3
	// BTN_ID_4 as defined in ugui/ugui.h:423
	BTN_ID_4 = OBJ_ID_4
	// BTN_ID_5 as defined in ugui/ugui.h:424
	BTN_ID_5 = OBJ_ID_5
	// BTN_ID_6 as defined in ugui/ugui.h:425
	BTN_ID_6 = OBJ_ID_6
	// BTN_ID_7 as defined in ugui/ugui.h:426
	BTN_ID_7 = OBJ_ID_7
	// BTN_ID_8 as defined in ugui/ugui.h:427
	BTN_ID_8 = OBJ_ID_8
	// BTN_ID_9 as defined in ugui/ugui.h:428
	BTN_ID_9 = OBJ_ID_9
	// BTN_ID_10 as defined in ugui/ugui.h:429
	BTN_ID_10 = OBJ_ID_10
	// BTN_ID_11 as defined in ugui/ugui.h:430
	BTN_ID_11 = OBJ_ID_11
	// BTN_ID_12 as defined in ugui/ugui.h:431
	BTN_ID_12 = OBJ_ID_12
	// BTN_ID_13 as defined in ugui/ugui.h:432
	BTN_ID_13 = OBJ_ID_13
	// BTN_ID_14 as defined in ugui/ugui.h:433
	BTN_ID_14 = OBJ_ID_14
	// BTN_ID_15 as defined in ugui/ugui.h:434
	BTN_ID_15 = OBJ_ID_15
	// BTN_ID_16 as defined in ugui/ugui.h:435
	BTN_ID_16 = OBJ_ID_16
	// BTN_ID_17 as defined in ugui/ugui.h:436
	BTN_ID_17 = OBJ_ID_17
	// BTN_ID_18 as defined in ugui/ugui.h:437
	BTN_ID_18 = OBJ_ID_18
	// BTN_ID_19 as defined in ugui/ugui.h:438
	BTN_ID_19 = OBJ_ID_19
	// BTN_STATE_RELEASED as defined in ugui/ugui.h:441
	BTN_STATE_RELEASED = (0 << 0)
	// BTN_STATE_PRESSED as defined in ugui/ugui.h:442
	BTN_STATE_PRESSED = (1 << 0)
	// BTN_STATE_ALWAYS_REDRAW as defined in ugui/ugui.h:443
	BTN_STATE_ALWAYS_REDRAW = (1 << 1)
	// BTN_STYLE_2D as defined in ugui/ugui.h:446
	BTN_STYLE_2D = (0 << 0)
	// BTN_STYLE_3D as defined in ugui/ugui.h:447
	BTN_STYLE_3D = (1 << 0)
	// BTN_STYLE_TOGGLE_COLORS as defined in ugui/ugui.h:448
	BTN_STYLE_TOGGLE_COLORS = (1 << 1)
	// BTN_STYLE_USE_ALTERNATE_COLORS as defined in ugui/ugui.h:449
	BTN_STYLE_USE_ALTERNATE_COLORS = (1 << 2)
	// BTN_STYLE_NO_BORDERS as defined in ugui/ugui.h:450
	BTN_STYLE_NO_BORDERS = (1 << 3)
	// BTN_STYLE_NO_FILL as defined in ugui/ugui.h:451
	BTN_STYLE_NO_FILL = (1 << 4)
	// BTN_EVENT_CLICKED as defined in ugui/ugui.h:454
	BTN_EVENT_CLICKED = OBJ_EVENT_CLICKED
	// CHB_ID_0 as defined in ugui/ugui.h:477
	CHB_ID_0 = OBJ_ID_0
	// CHB_ID_1 as defined in ugui/ugui.h:478
	CHB_ID_1 = OBJ_ID_1
	// CHB_ID_2 as defined in ugui/ugui.h:479
	CHB_ID_2 = OBJ_ID_2
	// CHB_ID_3 as defined in ugui/ugui.h:480
	CHB_ID_3 = OBJ_ID_3
	// CHB_ID_4 as defined in ugui/ugui.h:481
	CHB_ID_4 = OBJ_ID_4
	// CHB_ID_5 as defined in ugui/ugui.h:482
	CHB_ID_5 = OBJ_ID_5
	// CHB_ID_6 as defined in ugui/ugui.h:483
	CHB_ID_6 = OBJ_ID_6
	// CHB_ID_7 as defined in ugui/ugui.h:484
	CHB_ID_7 = OBJ_ID_7
	// CHB_ID_8 as defined in ugui/ugui.h:485
	CHB_ID_8 = OBJ_ID_8
	// CHB_ID_9 as defined in ugui/ugui.h:486
	CHB_ID_9 = OBJ_ID_9
	// CHB_ID_10 as defined in ugui/ugui.h:487
	CHB_ID_10 = OBJ_ID_10
	// CHB_ID_11 as defined in ugui/ugui.h:488
	CHB_ID_11 = OBJ_ID_11
	// CHB_ID_12 as defined in ugui/ugui.h:489
	CHB_ID_12 = OBJ_ID_12
	// CHB_ID_13 as defined in ugui/ugui.h:490
	CHB_ID_13 = OBJ_ID_13
	// CHB_ID_14 as defined in ugui/ugui.h:491
	CHB_ID_14 = OBJ_ID_14
	// CHB_ID_15 as defined in ugui/ugui.h:492
	CHB_ID_15 = OBJ_ID_15
	// CHB_ID_16 as defined in ugui/ugui.h:493
	CHB_ID_16 = OBJ_ID_16
	// CHB_ID_17 as defined in ugui/ugui.h:494
	CHB_ID_17 = OBJ_ID_17
	// CHB_ID_18 as defined in ugui/ugui.h:495
	CHB_ID_18 = OBJ_ID_18
	// CHB_ID_19 as defined in ugui/ugui.h:496
	CHB_ID_19 = OBJ_ID_19
	// CHB_STATE_RELEASED as defined in ugui/ugui.h:499
	CHB_STATE_RELEASED = (0 << 0)
	// CHB_STATE_PRESSED as defined in ugui/ugui.h:500
	CHB_STATE_PRESSED = (1 << 0)
	// CHB_STATE_ALWAYS_REDRAW as defined in ugui/ugui.h:501
	CHB_STATE_ALWAYS_REDRAW = (1 << 1)
	// CHB_STYLE_2D as defined in ugui/ugui.h:504
	CHB_STYLE_2D = (0 << 0)
	// CHB_STYLE_3D as defined in ugui/ugui.h:505
	CHB_STYLE_3D = (1 << 0)
	// CHB_STYLE_TOGGLE_COLORS as defined in ugui/ugui.h:506
	CHB_STYLE_TOGGLE_COLORS = (1 << 1)
	// CHB_STYLE_USE_ALTERNATE_COLORS as defined in ugui/ugui.h:507
	CHB_STYLE_USE_ALTERNATE_COLORS = (1 << 2)
	// CHB_STYLE_NO_BORDERS as defined in ugui/ugui.h:508
	CHB_STYLE_NO_BORDERS = (1 << 3)
	// CHB_STYLE_NO_FILL as defined in ugui/ugui.h:509
	CHB_STYLE_NO_FILL = (1 << 4)
	// CHB_EVENT_CLICKED as defined in ugui/ugui.h:512
	CHB_EVENT_CLICKED = OBJ_EVENT_CLICKED
	// TXB_ID_0 as defined in ugui/ugui.h:532
	TXB_ID_0 = OBJ_ID_0
	// TXB_ID_1 as defined in ugui/ugui.h:533
	TXB_ID_1 = OBJ_ID_1
	// TXB_ID_2 as defined in ugui/ugui.h:534
	TXB_ID_2 = OBJ_ID_2
	// TXB_ID_3 as defined in ugui/ugui.h:535
	TXB_ID_3 = OBJ_ID_3
	// TXB_ID_4 as defined in ugui/ugui.h:536
	TXB_ID_4 = OBJ_ID_4
	// TXB_ID_5 as defined in ugui/ugui.h:537
	TXB_ID_5 = OBJ_ID_5
	// TXB_ID_6 as defined in ugui/ugui.h:538
	TXB_ID_6 = OBJ_ID_6
	// TXB_ID_7 as defined in ugui/ugui.h:539
	TXB_ID_7 = OBJ_ID_7
	// TXB_ID_8 as defined in ugui/ugui.h:540
	TXB_ID_8 = OBJ_ID_8
	// TXB_ID_9 as defined in ugui/ugui.h:541
	TXB_ID_9 = OBJ_ID_9
	// TXB_ID_10 as defined in ugui/ugui.h:542
	TXB_ID_10 = OBJ_ID_10
	// TXB_ID_11 as defined in ugui/ugui.h:543
	TXB_ID_11 = OBJ_ID_11
	// TXB_ID_12 as defined in ugui/ugui.h:544
	TXB_ID_12 = OBJ_ID_12
	// TXB_ID_13 as defined in ugui/ugui.h:545
	TXB_ID_13 = OBJ_ID_13
	// TXB_ID_14 as defined in ugui/ugui.h:546
	TXB_ID_14 = OBJ_ID_14
	// TXB_ID_15 as defined in ugui/ugui.h:547
	TXB_ID_15 = OBJ_ID_15
	// TXB_ID_16 as defined in ugui/ugui.h:548
	TXB_ID_16 = OBJ_ID_16
	// TXB_ID_17 as defined in ugui/ugui.h:549
	TXB_ID_17 = OBJ_ID_17
	// TXB_ID_18 as defined in ugui/ugui.h:550
	TXB_ID_18 = OBJ_ID_18
	// TXB_ID_19 as defined in ugui/ugui.h:551
	TXB_ID_19 = OBJ_ID_19
	// IMG_ID_0 as defined in ugui/ugui.h:564
	IMG_ID_0 = OBJ_ID_0
	// IMG_ID_1 as defined in ugui/ugui.h:565
	IMG_ID_1 = OBJ_ID_1
	// IMG_ID_2 as defined in ugui/ugui.h:566
	IMG_ID_2 = OBJ_ID_2
	// IMG_ID_3 as defined in ugui/ugui.h:567
	IMG_ID_3 = OBJ_ID_3
	// IMG_ID_4 as defined in ugui/ugui.h:568
	IMG_ID_4 = OBJ_ID_4
	// IMG_ID_5 as defined in ugui/ugui.h:569
	IMG_ID_5 = OBJ_ID_5
	// IMG_ID_6 as defined in ugui/ugui.h:570
	IMG_ID_6 = OBJ_ID_6
	// IMG_ID_7 as defined in ugui/ugui.h:571
	IMG_ID_7 = OBJ_ID_7
	// IMG_ID_8 as defined in ugui/ugui.h:572
	IMG_ID_8 = OBJ_ID_8
	// IMG_ID_9 as defined in ugui/ugui.h:573
	IMG_ID_9 = OBJ_ID_9
	// IMG_ID_10 as defined in ugui/ugui.h:574
	IMG_ID_10 = OBJ_ID_10
	// IMG_ID_11 as defined in ugui/ugui.h:575
	IMG_ID_11 = OBJ_ID_11
	// IMG_ID_12 as defined in ugui/ugui.h:576
	IMG_ID_12 = OBJ_ID_12
	// IMG_ID_13 as defined in ugui/ugui.h:577
	IMG_ID_13 = OBJ_ID_13
	// IMG_ID_14 as defined in ugui/ugui.h:578
	IMG_ID_14 = OBJ_ID_14
	// IMG_ID_15 as defined in ugui/ugui.h:579
	IMG_ID_15 = OBJ_ID_15
	// IMG_ID_16 as defined in ugui/ugui.h:580
	IMG_ID_16 = OBJ_ID_16
	// IMG_ID_17 as defined in ugui/ugui.h:581
	IMG_ID_17 = OBJ_ID_17
	// IMG_ID_18 as defined in ugui/ugui.h:582
	IMG_ID_18 = OBJ_ID_18
	// IMG_ID_19 as defined in ugui/ugui.h:583
	IMG_ID_19 = OBJ_ID_19
	// IMG_TYPE_BMP as defined in ugui/ugui.h:586
	IMG_TYPE_BMP = (1 << 0)
	// UG_SATUS_WAIT_FOR_UPDATE as defined in ugui/ugui.h:643
	UG_SATUS_WAIT_FOR_UPDATE = (1 << 0)
	// C_MAROON as defined in ugui/ugui.h:792
	C_MAROON = 0x800000
	// C_DARK_RED as defined in ugui/ugui.h:793
	C_DARK_RED = 0x8B0000
	// C_BROWN as defined in ugui/ugui.h:794
	C_BROWN = 0xA52A2A
	// C_FIREBRICK as defined in ugui/ugui.h:795
	C_FIREBRICK = 0xB22222
	// C_CRIMSON as defined in ugui/ugui.h:796
	C_CRIMSON = 0xDC143C
	// C_RED as defined in ugui/ugui.h:797
	C_RED = 0xFF0000
	// C_TOMATO as defined in ugui/ugui.h:798
	C_TOMATO = 0xFF6347
	// C_CORAL as defined in ugui/ugui.h:799
	C_CORAL = 0xFF7F50
	// C_INDIAN_RED as defined in ugui/ugui.h:800
	C_INDIAN_RED = 0xCD5C5C
	// C_LIGHT_CORAL as defined in ugui/ugui.h:801
	C_LIGHT_CORAL = 0xF08080
	// C_DARK_SALMON as defined in ugui/ugui.h:802
	C_DARK_SALMON = 0xE9967A
	// C_SALMON as defined in ugui/ugui.h:803
	C_SALMON = 0xFA8072
	// C_LIGHT_SALMON as defined in ugui/ugui.h:804
	C_LIGHT_SALMON = 0xFFA07A
	// C_ORANGE_RED as defined in ugui/ugui.h:805
	C_ORANGE_RED = 0xFF4500
	// C_DARK_ORANGE as defined in ugui/ugui.h:806
	C_DARK_ORANGE = 0xFF8C00
	// C_ORANGE as defined in ugui/ugui.h:807
	C_ORANGE = 0xFFA500
	// C_GOLD as defined in ugui/ugui.h:808
	C_GOLD = 0xFFD700
	// C_DARK_GOLDEN_ROD as defined in ugui/ugui.h:809
	C_DARK_GOLDEN_ROD = 0xB8860B
	// C_GOLDEN_ROD as defined in ugui/ugui.h:810
	C_GOLDEN_ROD = 0xDAA520
	// C_PALE_GOLDEN_ROD as defined in ugui/ugui.h:811
	C_PALE_GOLDEN_ROD = 0xEEE8AA
	// C_DARK_KHAKI as defined in ugui/ugui.h:812
	C_DARK_KHAKI = 0xBDB76B
	// C_KHAKI as defined in ugui/ugui.h:813
	C_KHAKI = 0xF0E68C
	// C_OLIVE as defined in ugui/ugui.h:814
	C_OLIVE = 0x808000
	// C_YELLOW as defined in ugui/ugui.h:815
	C_YELLOW = 0xFFFF00
	// C_YELLOW_GREEN as defined in ugui/ugui.h:816
	C_YELLOW_GREEN = 0x9ACD32
	// C_DARK_OLIVE_GREEN as defined in ugui/ugui.h:817
	C_DARK_OLIVE_GREEN = 0x556B2F
	// C_OLIVE_DRAB as defined in ugui/ugui.h:818
	C_OLIVE_DRAB = 0x6B8E23
	// C_LAWN_GREEN as defined in ugui/ugui.h:819
	C_LAWN_GREEN = 0x7CFC00
	// C_CHART_REUSE as defined in ugui/ugui.h:820
	C_CHART_REUSE = 0x7FFF00
	// C_GREEN_YELLOW as defined in ugui/ugui.h:821
	C_GREEN_YELLOW = 0xADFF2F
	// C_DARK_GREEN as defined in ugui/ugui.h:822
	C_DARK_GREEN = 0x006400
	// C_GREEN as defined in ugui/ugui.h:823
	C_GREEN = 0x00FF00
	// C_FOREST_GREEN as defined in ugui/ugui.h:824
	C_FOREST_GREEN = 0x228B22
	// C_LIME as defined in ugui/ugui.h:825
	C_LIME = 0x00FF00
	// C_LIME_GREEN as defined in ugui/ugui.h:826
	C_LIME_GREEN = 0x32CD32
	// C_LIGHT_GREEN as defined in ugui/ugui.h:827
	C_LIGHT_GREEN = 0x90EE90
	// C_PALE_GREEN as defined in ugui/ugui.h:828
	C_PALE_GREEN = 0x98FB98
	// C_DARK_SEA_GREEN as defined in ugui/ugui.h:829
	C_DARK_SEA_GREEN = 0x8FBC8F
	// C_MEDIUM_SPRING_GREEN as defined in ugui/ugui.h:830
	C_MEDIUM_SPRING_GREEN = 0x00FA9A
	// C_SPRING_GREEN as defined in ugui/ugui.h:831
	C_SPRING_GREEN = 0x00FF7F
	// C_SEA_GREEN as defined in ugui/ugui.h:832
	C_SEA_GREEN = 0x2E8B57
	// C_MEDIUM_AQUA_MARINE as defined in ugui/ugui.h:833
	C_MEDIUM_AQUA_MARINE = 0x66CDAA
	// C_MEDIUM_SEA_GREEN as defined in ugui/ugui.h:834
	C_MEDIUM_SEA_GREEN = 0x3CB371
	// C_LIGHT_SEA_GREEN as defined in ugui/ugui.h:835
	C_LIGHT_SEA_GREEN = 0x20B2AA
	// C_DARK_SLATE_GRAY as defined in ugui/ugui.h:836
	C_DARK_SLATE_GRAY = 0x2F4F4F
	// C_TEAL as defined in ugui/ugui.h:837
	C_TEAL = 0x008080
	// C_DARK_CYAN as defined in ugui/ugui.h:838
	C_DARK_CYAN = 0x008B8B
	// C_AQUA as defined in ugui/ugui.h:839
	C_AQUA = 0x00FFFF
	// C_CYAN as defined in ugui/ugui.h:840
	C_CYAN = 0x00FFFF
	// C_LIGHT_CYAN as defined in ugui/ugui.h:841
	C_LIGHT_CYAN = 0xE0FFFF
	// C_DARK_TURQUOISE as defined in ugui/ugui.h:842
	C_DARK_TURQUOISE = 0x00CED1
	// C_TURQUOISE as defined in ugui/ugui.h:843
	C_TURQUOISE = 0x40E0D0
	// C_MEDIUM_TURQUOISE as defined in ugui/ugui.h:844
	C_MEDIUM_TURQUOISE = 0x48D1CC
	// C_PALE_TURQUOISE as defined in ugui/ugui.h:845
	C_PALE_TURQUOISE = 0xAFEEEE
	// C_AQUA_MARINE as defined in ugui/ugui.h:846
	C_AQUA_MARINE = 0x7FFFD4
	// C_POWDER_BLUE as defined in ugui/ugui.h:847
	C_POWDER_BLUE = 0xB0E0E6
	// C_CADET_BLUE as defined in ugui/ugui.h:848
	C_CADET_BLUE = 0x5F9EA0
	// C_STEEL_BLUE as defined in ugui/ugui.h:849
	C_STEEL_BLUE = 0x4682B4
	// C_CORN_FLOWER_BLUE as defined in ugui/ugui.h:850
	C_CORN_FLOWER_BLUE = 0x6495ED
	// C_DEEP_SKY_BLUE as defined in ugui/ugui.h:851
	C_DEEP_SKY_BLUE = 0x00BFFF
	// C_DODGER_BLUE as defined in ugui/ugui.h:852
	C_DODGER_BLUE = 0x1E90FF
	// C_LIGHT_BLUE as defined in ugui/ugui.h:853
	C_LIGHT_BLUE = 0xADD8E6
	// C_SKY_BLUE as defined in ugui/ugui.h:854
	C_SKY_BLUE = 0x87CEEB
	// C_LIGHT_SKY_BLUE as defined in ugui/ugui.h:855
	C_LIGHT_SKY_BLUE = 0x87CEFA
	// C_MIDNIGHT_BLUE as defined in ugui/ugui.h:856
	C_MIDNIGHT_BLUE = 0x191970
	// C_NAVY as defined in ugui/ugui.h:857
	C_NAVY = 0x000080
	// C_DARK_BLUE as defined in ugui/ugui.h:858
	C_DARK_BLUE = 0x00008B
	// C_MEDIUM_BLUE as defined in ugui/ugui.h:859
	C_MEDIUM_BLUE = 0x0000CD
	// C_BLUE as defined in ugui/ugui.h:860
	C_BLUE = 255
	// C_ROYAL_BLUE as defined in ugui/ugui.h:861
	C_ROYAL_BLUE = 0x4169E1
	// C_BLUE_VIOLET as defined in ugui/ugui.h:862
	C_BLUE_VIOLET = 0x8A2BE2
	// C_INDIGO as defined in ugui/ugui.h:863
	C_INDIGO = 0x4B0082
	// C_DARK_SLATE_BLUE as defined in ugui/ugui.h:864
	C_DARK_SLATE_BLUE = 0x483D8B
	// C_SLATE_BLUE as defined in ugui/ugui.h:865
	C_SLATE_BLUE = 0x6A5ACD
	// C_MEDIUM_SLATE_BLUE as defined in ugui/ugui.h:866
	C_MEDIUM_SLATE_BLUE = 0x7B68EE
	// C_MEDIUM_PURPLE as defined in ugui/ugui.h:867
	C_MEDIUM_PURPLE = 0x9370DB
	// C_DARK_MAGENTA as defined in ugui/ugui.h:868
	C_DARK_MAGENTA = 0x8B008B
	// C_DARK_VIOLET as defined in ugui/ugui.h:869
	C_DARK_VIOLET = 0x9400D3
	// C_DARK_ORCHID as defined in ugui/ugui.h:870
	C_DARK_ORCHID = 0x9932CC
	// C_MEDIUM_ORCHID as defined in ugui/ugui.h:871
	C_MEDIUM_ORCHID = 0xBA55D3
	// C_PURPLE as defined in ugui/ugui.h:872
	C_PURPLE = 0x800080
	// C_THISTLE as defined in ugui/ugui.h:873
	C_THISTLE = 0xD8BFD8
	// C_PLUM as defined in ugui/ugui.h:874
	C_PLUM = 0xDDA0DD
	// C_VIOLET as defined in ugui/ugui.h:875
	C_VIOLET = 0xEE82EE
	// C_MAGENTA as defined in ugui/ugui.h:876
	C_MAGENTA = 0xFF00FF
	// C_ORCHID as defined in ugui/ugui.h:877
	C_ORCHID = 0xDA70D6
	// C_MEDIUM_VIOLET_RED as defined in ugui/ugui.h:878
	C_MEDIUM_VIOLET_RED = 0xC71585
	// C_PALE_VIOLET_RED as defined in ugui/ugui.h:879
	C_PALE_VIOLET_RED = 0xDB7093
	// C_DEEP_PINK as defined in ugui/ugui.h:880
	C_DEEP_PINK = 0xFF1493
	// C_HOT_PINK as defined in ugui/ugui.h:881
	C_HOT_PINK = 0xFF69B4
	// C_LIGHT_PINK as defined in ugui/ugui.h:882
	C_LIGHT_PINK = 0xFFB6C1
	// C_PINK as defined in ugui/ugui.h:883
	C_PINK = 0xFFC0CB
	// C_ANTIQUE_WHITE as defined in ugui/ugui.h:884
	C_ANTIQUE_WHITE = 0xFAEBD7
	// C_BEIGE as defined in ugui/ugui.h:885
	C_BEIGE = 0xF5F5DC
	// C_BISQUE as defined in ugui/ugui.h:886
	C_BISQUE = 0xFFE4C4
	// C_BLANCHED_ALMOND as defined in ugui/ugui.h:887
	C_BLANCHED_ALMOND = 0xFFEBCD
	// C_WHEAT as defined in ugui/ugui.h:888
	C_WHEAT = 0xF5DEB3
	// C_CORN_SILK as defined in ugui/ugui.h:889
	C_CORN_SILK = 0xFFF8DC
	// C_LEMON_CHIFFON as defined in ugui/ugui.h:890
	C_LEMON_CHIFFON = 0xFFFACD
	// C_LIGHT_GOLDEN_ROD_YELLOW as defined in ugui/ugui.h:891
	C_LIGHT_GOLDEN_ROD_YELLOW = 0xFAFAD2
	// C_LIGHT_YELLOW as defined in ugui/ugui.h:892
	C_LIGHT_YELLOW = 0xFFFFE0
	// C_SADDLE_BROWN as defined in ugui/ugui.h:893
	C_SADDLE_BROWN = 0x8B4513
	// C_SIENNA as defined in ugui/ugui.h:894
	C_SIENNA = 0xA0522D
	// C_CHOCOLATE as defined in ugui/ugui.h:895
	C_CHOCOLATE = 0xD2691E
	// C_PERU as defined in ugui/ugui.h:896
	C_PERU = 0xCD853F
	// C_SANDY_BROWN as defined in ugui/ugui.h:897
	C_SANDY_BROWN = 0xF4A460
	// C_BURLY_WOOD as defined in ugui/ugui.h:898
	C_BURLY_WOOD = 0xDEB887
	// C_TAN as defined in ugui/ugui.h:899
	C_TAN = 0xD2B48C
	// C_ROSY_BROWN as defined in ugui/ugui.h:900
	C_ROSY_BROWN = 0xBC8F8F
	// C_MOCCASIN as defined in ugui/ugui.h:901
	C_MOCCASIN = 0xFFE4B5
	// C_NAVAJO_WHITE as defined in ugui/ugui.h:902
	C_NAVAJO_WHITE = 0xFFDEAD
	// C_PEACH_PUFF as defined in ugui/ugui.h:903
	C_PEACH_PUFF = 0xFFDAB9
	// C_MISTY_ROSE as defined in ugui/ugui.h:904
	C_MISTY_ROSE = 0xFFE4E1
	// C_LAVENDER_BLUSH as defined in ugui/ugui.h:905
	C_LAVENDER_BLUSH = 0xFFF0F5
	// C_LINEN as defined in ugui/ugui.h:906
	C_LINEN = 0xFAF0E6
	// C_OLD_LACE as defined in ugui/ugui.h:907
	C_OLD_LACE = 0xFDF5E6
	// C_PAPAYA_WHIP as defined in ugui/ugui.h:908
	C_PAPAYA_WHIP = 0xFFEFD5
	// C_SEA_SHELL as defined in ugui/ugui.h:909
	C_SEA_SHELL = 0xFFF5EE
	// C_MINT_CREAM as defined in ugui/ugui.h:910
	C_MINT_CREAM = 0xF5FFFA
	// C_SLATE_GRAY as defined in ugui/ugui.h:911
	C_SLATE_GRAY = 0x708090
	// C_LIGHT_SLATE_GRAY as defined in ugui/ugui.h:912
	C_LIGHT_SLATE_GRAY = 0x778899
	// C_LIGHT_STEEL_BLUE as defined in ugui/ugui.h:913
	C_LIGHT_STEEL_BLUE = 0xB0C4DE
	// C_LAVENDER as defined in ugui/ugui.h:914
	C_LAVENDER = 0xE6E6FA
	// C_FLORAL_WHITE as defined in ugui/ugui.h:915
	C_FLORAL_WHITE = 0xFFFAF0
	// C_ALICE_BLUE as defined in ugui/ugui.h:916
	C_ALICE_BLUE = 0xF0F8FF
	// C_GHOST_WHITE as defined in ugui/ugui.h:917
	C_GHOST_WHITE = 0xF8F8FF
	// C_HONEYDEW as defined in ugui/ugui.h:918
	C_HONEYDEW = 0xF0FFF0
	// C_IVORY as defined in ugui/ugui.h:919
	C_IVORY = 0xFFFFF0
	// C_AZURE as defined in ugui/ugui.h:920
	C_AZURE = 0xF0FFFF
	// C_SNOW as defined in ugui/ugui.h:921
	C_SNOW = 0xFFFAFA
	// C_BLACK as defined in ugui/ugui.h:922
	C_BLACK = 0
	// C_DIM_GRAY as defined in ugui/ugui.h:923
	C_DIM_GRAY = 0x696969
	// C_GRAY as defined in ugui/ugui.h:924
	C_GRAY = 8421504
	// C_DARK_GRAY as defined in ugui/ugui.h:925
	C_DARK_GRAY = 0xA9A9A9
	// C_SILVER as defined in ugui/ugui.h:926
	C_SILVER = 0xC0C0C0
	// C_LIGHT_GRAY as defined in ugui/ugui.h:927
	C_LIGHT_GRAY = 0xD3D3D3
	// C_GAINSBORO as defined in ugui/ugui.h:928
	C_GAINSBORO = 0xDCDCDC
	// C_WHITE_SMOKE as defined in ugui/ugui.h:929
	C_WHITE_SMOKE = 0xF5F5F5
	// C_WHITE as defined in ugui/ugui.h:930
	C_WHITE = 16777215
	// UG_MAX_TEXT_LEN as defined in ugui/ugui_config.h:44
	UG_MAX_TEXT_LEN = 255
)

// FONT_TYPE as declared in ugui/ugui.h:32
type FONT_TYPE int32

// FONT_TYPE enumeration from ugui/ugui.h:32
const (
	FONT_TYPE_1BPP FONT_TYPE = iota
	FONT_TYPE_8BPP FONT_TYPE = 1
)

// FONT_ID as declared in ugui/ugui.h:52
type FONT_ID int32

// FONT_ID enumeration from ugui/ugui.h:52
const (
	FONT_ID_4X6   FONT_ID = iota
	FONT_ID_5X8   FONT_ID = 1
	FONT_ID_5X12  FONT_ID = 2
	FONT_ID_6X8   FONT_ID = 3
	FONT_ID_6X10  FONT_ID = 4
	FONT_ID_7X12  FONT_ID = 5
	FONT_ID_8X8   FONT_ID = 6
	FONT_ID_8X12  FONT_ID = 7
	FONT_ID_8X14  FONT_ID = 8
	FONT_ID_10X16 FONT_ID = 9
	FONT_ID_12X16 FONT_ID = 10
	FONT_ID_12X20 FONT_ID = 11
	FONT_ID_16X26 FONT_ID = 12
	FONT_ID_22X36 FONT_ID = 13
	FONT_ID_24X40 FONT_ID = 14
	FONT_ID_32X53 FONT_ID = 15
)

const ()
