// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 12 Dec 2023 23:18:54 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package lvgl provides Go bindings for libgougui.
*/
package ug
