// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 21 Nov 2023 19:54:43 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package lvgl provides Go bindings for libgougui.
*/
package ug
